# Generated by Django 2.1.3 on 2018-12-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='MapSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('stay', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('days', models.IntegerField(blank=True)),
                ('style', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('content', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TouristSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_order', models.IntegerField()),
                ('site_name', models.CharField(max_length=100)),
                ('time', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('site_content', models.TextField(blank=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TotalCourse')),
            ],
            options={
                'ordering': ['route_order'],
            },
        ),
    ]
