# Generated by Django 2.1.3 on 2018-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_touristsite_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='style',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
