# Generated by Django 2.1.2 on 2018-11-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('days', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('seq', models.IntegerField(blank=True)),
                ('day', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True)),
                ('site_content', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TouristSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_order', models.IntegerField()),
                ('site_name', models.CharField(max_length=100)),
                ('time', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TotalCourse')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Schedule_content'),
        ),
    ]
