# Generated by Django 2.1.2 on 2018-11-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20181128_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcourse',
            name='site_content',
        ),
        migrations.AddField(
            model_name='touristsite',
            name='site_content',
            field=models.TextField(blank=True),
        ),
    ]
