# Generated by Django 2.1.3 on 2018-11-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20181127_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Schedule'),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TotalCourse'),
        ),
    ]
