# Generated by Django 2.1.3 on 2018-11-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20181127_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristsite',
            options={'ordering': ['route_order']},
        ),
    ]
