# Generated by Django 2.1.2 on 2018-12-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20181204_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsite',
            name='site_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
