# Generated by Django 2.1.3 on 2018-12-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20181201_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcourse',
            name='site_content',
        ),
        migrations.AddField(
            model_name='touristsite',
            name='site_content',
            field=models.TextField(blank=True),
        ),
    ]
