# Generated by Django 2.1.3 on 2018-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20181217_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
