# Generated by Django 2.1.2 on 2018-12-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_schedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsite',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
