# Generated by Django 2.1.3 on 2018-12-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20181204_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsite',
            name='site_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
